//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinica_Kareni_Axel.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Mobelo_ClinicaContainer : DbContext
    {
        public Mobelo_ClinicaContainer()
            : base("name=Mobelo_ClinicaContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Bitacora> Bitacoras { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Familia> Familias { get; set; }
        public virtual DbSet<Mascota> Mascotas { get; set; }
        public virtual DbSet<HistorialMedico> HistorialMedicos { get; set; }
        public virtual DbSet<Vacuna> Vacunas { get; set; }
    }
}
